/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hfeng' at '15-5-2 下午9:19' with Gradle 2.3
 *
 * @author hfeng, @date 15-5-2 下午9:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
